version: '3'
services:

  videogamecatalogue:
    #    see info at https://hub.docker.com/r/payara/server-full/
    image: videogamecatalogue
    container_name: videogamecatalogue
    restart: always
    depends_on:
      - videogamecatalogue-db
    ports:
      - "9080:8080" # web
      - "9081:8181" # web https
      - "9048:4848" # admin
      - "9009:9009" # debug

  videogamecatalogue-db:
    image: postgres
    restart: always
    container_name: videogamecatalogue-db
    #    user: "1000:1000"
    volumes:
      - videogamecatalogue:/var/lib/postgresql/data
    #      - ./db-init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=videogamecatalogue
      - POSTGRES_USER=postgres # default user will all permissions, should create another user usually
      - POSTGRES_PASSWORD=d3f4ult
    ports:
      - "9054:5432"

volumes:
  videogamecatalogue: